from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.ui import WebDriverWait


class UIInteractions:
    timeout = 10

    @staticmethod
    def waiting_for_element_visibility(driver, locator):
        return WebDriverWait(driver, UIInteractions.timeout).until(
            ec.visibility_of_element_located(locator))

    @staticmethod
    def waiting_for_element_is_clickable(driver, locator):
        return WebDriverWait(driver, UIInteractions.timeout).until(
            ec.element_to_be_clickable(locator))

    @staticmethod
    def click(driver, locator):
        UIInteractions.waiting_for_element_is_clickable(driver, locator).click()

    @staticmethod
    def input_text_value(driver, locator, value):
        UIInteractions.waiting_for_element_visibility(driver, locator).send_keys(value)

    @staticmethod
    def input_issue_value(driver, locator, value):
        UIInteractions.waiting_for_element_is_clickable(driver, locator).click()
        UIInteractions.waiting_for_element_visibility(driver, locator).send_keys(Keys.DELETE)
        UIInteractions.waiting_for_element_visibility(driver, locator).send_keys(value)
        UIInteractions.waiting_for_element_visibility(driver, locator).send_keys(Keys.ENTER)

    @staticmethod
    def submit(driver, locator):
        UIInteractions.waiting_for_element_visibility(driver, locator).submit()

    @staticmethod
    def get_text(driver, locator):
        return UIInteractions.waiting_for_element_visibility(driver, locator).text

    @staticmethod
    def sing_sen_maker():
        s_nouns = ["A dude", "My mom", "The king", "Some guy", "A cat with rabies", "A sloth", "Your homie",
                   "This cool guy my gardener met yesterday", "Superman", 'Human Resources Manager', 'Accountant IV',
                   'Desktop Support Technician', 'General Manager', 'Actuary', 'Biostatistician III',
                   'Financial Analyst', 'Senior Cost Accountant', 'Civil Engineer', 'Marketing Assistant', 'Professor',
                   'GIS Technical Architect', 'Office Assistant I', 'Director of Sales', 'Operator',
                   'Associate Professor', 'Senior Editor', 'Tax Accountant', 'Help Desk Operator',
                   'Nuclear Power Engineer', 'Sales Associate', 'Actuary', 'Office Assistant I', 'Research Associate',
                   'Senior Sales Associate', 'Account Executive', 'Account Executive', 'VP Marketing', 'VP Sales',
                   'Human Resources Manager', 'Actuary', 'Administrative Assistant IV', 'Actuary', 'Social Worker',
                   'Chief Design Engineer', 'Graphic Designer', 'VP Marketing', 'Assistant Manager',
                   'Senior Cost Accountant', 'Administrative Assistant III', 'Software Test Engineer II',
                   'Human Resources Assistant IV', 'Dental Hygienist', 'Project Manager', 'Administrative Officer',
                   'Environmental Tech', 'Account Representative II', 'Associate Professor', 'Programmer Analyst III',
                   'Health Coach I', 'Research Associate', 'Administrative Assistant IV', 'Junior Executive',
                   'Registered Nurse', 'Office Assistant IV', 'Librarian', 'Librarian', 'Occupational Therapist',
                   'Financial Advisor', 'Senior Developer', 'Staff Accountant II', 'Speech Pathologist',
                   'Research Assistant IV', 'Accountant IV', 'VP Quality Control', 'Executive Secretary',
                   'Accounting Assistant III', 'Director of Sales', 'Research Assistant I',
                   'Human Resources Assistant III', 'Accountant II', 'Safety Technician I', 'Technical Writer',
                   'VP Marketing', 'Help Desk Operator', 'Senior Quality Engineer', 'Financial Analyst',
                   'Office Assistant IV', 'Programmer III', 'Help Desk Technician', 'Recruiting Manager',
                   'Human Resources Assistant I', 'Librarian', 'Dental Hygienist', 'General Manager',
                   'Staff Accountant I', 'Research Assistant III', 'Research Nurse', 'Paralegal', 'VP Marketing',
                   'Budget/Accounting Analyst IV', 'Help Desk Operator', 'Nurse Practicioner',
                   'Quality Control Specialist', 'VP Marketing', 'Programmer IV', 'Web Designer II',
                   'Human Resources Manager', 'Junior Executive', 'Tax Accountant', 'Editor', 'Biostatistician I',
                   'Structural Engineer', 'Statistician I', 'Software Test Engineer III', 'Research Associate',
                   'Editor', 'Software Consultant', 'Accountant III', 'Occupational Therapist', 'VP Sales',
                   'Desktop Support Technician', 'Senior Sales Associate', 'Clinical Specialist', 'Analyst Programmer',
                   'Geologist I', 'Graphic Designer', 'Research Associate', 'Structural Analysis Engineer',
                   'Biostatistician I', 'Registered Nurse', 'VP Marketing', 'Database Administrator III',
                   'Geological Engineer', 'Office Assistant IV', 'Marketing Manager', 'Staff Accountant II',
                   'Occupational Therapist', 'VP Quality Control', 'Paralegal', 'Research Associate',
                   'Physical Therapy Assistant', 'Pharmacist', 'Pharmacist', 'Account Executive', 'Media Manager IV',
                   'GIS Technical Architect', 'Budget/Accounting Analyst I', 'Senior Developer', 'Structural Engineer',
                   'Assistant Manager', 'Database Administrator III', 'VP Marketing', 'Office Assistant III',
                   'Tax Accountant', 'Software Consultant', 'Biostatistician IV', 'Senior Cost Accountant',
                   'VP Marketing', 'Executive Secretary', 'Pharmacist', 'Programmer Analyst IV', 'Programmer I',
                   'Assistant Professor', 'Civil Engineer', 'Registered Nurse', 'Statistician I', 'Staff Accountant IV',
                   'Mechanical Systems Engineer', 'Design Engineer', 'Financial Advisor', 'VP Accounting',
                   'Nurse Practicioner', 'General Manager', 'Software Engineer I', 'Safety Technician IV',
                   'Accounting Assistant II', 'Registered Nurse', 'Chemical Engineer', 'Marketing Manager',
                   'Nuclear Power Engineer', 'Quality Control Specialist', 'Automation Specialist II',
                   'VP Product Management', 'Statistician IV', 'Payment Adjustment Coordinator',
                   'VP Product Management', 'Engineer III', 'Legal Assistant', 'Recruiting Manager',
                   'Biostatistician III', 'Legal Assistant', 'Executive Secretary', 'Database Administrator II',
                   'Financial Analyst', 'Statistician IV', 'Nuclear Power Engineer', 'Cost Accountant',
                   'Geological Engineer', 'Teacher', 'General Manager', 'Design Engineer', 'Speech Pathologist',
                   'Assistant Professor', 'Mechanical Systems Engineer', 'Health Coach III',
                   'Analog Circuit Design manager', 'Assistant Media Planner', 'Human Resources Assistant II',
                   'Operator', 'Cost Accountant', 'Tax Accountant', 'Biostatistician III', 'Account Representative III',
                   'Developer III', 'Automation Specialist IV', 'Operator', 'Geological Engineer', 'Dental Hygienist',
                   'Help Desk Operator', 'Legal Assistant', 'VP Marketing', 'Human Resources Assistant II',
                   'Civil Engineer', 'Programmer Analyst II', 'Professor', 'Automation Specialist II',
                   'Electrical Engineer', 'Nurse', 'Web Designer I', 'Automation Specialist IV', 'Pharmacist',
                   'Actuary', 'General Manager', 'Help Desk Operator', 'Geological Engineer', 'Design Engineer',
                   'VP Marketing', 'Accounting Assistant III', 'Occupational Therapist', 'Compensation Analyst',
                   'Junior Executive', 'Administrative Officer', 'Programmer Analyst IV', 'Account Executive',
                   'Senior Cost Accountant', 'Senior Quality Engineer', 'Civil Engineer', 'VP Accounting',
                   'Assistant Media Planner', 'Accountant I', 'Nuclear Power Engineer', 'Professor', 'Technical Writer',
                   'Recruiter', 'Staff Accountant II', 'Occupational Therapist', 'Staff Accountant II',
                   'Sales Associate', 'Director of Sales', 'Environmental Tech', 'Research Assistant II',
                   'Tax Accountant', 'Senior Developer', 'Data Coordiator', 'Junior Executive', 'Office Assistant II',
                   'Recruiting Manager', 'Programmer Analyst IV', 'Teacher', 'Research Nurse',
                   'Assistant Media Planner', 'VP Quality Control', 'Payment Adjustment Coordinator', 'VP Accounting',
                   'Environmental Specialist', 'Internal Auditor', 'Statistician IV', 'Professor', 'Civil Engineer',
                   'Design Engineer', 'Senior Editor', 'Junior Executive', 'Cost Accountant', 'Pharmacist',
                   'Analog Circuit Design manager', 'Environmental Specialist', 'Physical Therapy Assistant',
                   'Senior Financial Analyst', 'Geologist II', 'Electrical Engineer', 'Analog Circuit Design manager',
                   'Design Engineer', 'Human Resources Assistant IV', 'Graphic Designer', 'Senior Editor',
                   'Business Systems Development Analyst', 'Geological Engineer', 'Operator', 'Staff Accountant I',
                   'Help Desk Operator', 'Systems Administrator I', 'Environmental Specialist', 'VP Sales',
                   'GIS Technical Architect', 'Environmental Tech', 'Programmer Analyst II', 'Help Desk Technician',
                   'Web Designer IV', 'Design Engineer', 'Mechanical Systems Engineer', 'Geologist IV', 'Engineer III',
                   'Clinical Specialist', 'Account Coordinator', 'Account Executive', 'Software Test Engineer III',
                   'Executive Secretary', 'Research Assistant II', 'Software Test Engineer I', 'Nurse',
                   'Technical Writer', 'Data Coordiator', 'Programmer II', 'Food Chemist', 'Software Test Engineer I',
                   'Senior Developer', 'Sales Representative', 'Librarian', 'Project Manager', 'VP Marketing',
                   'Occupational Therapist', 'Senior Cost Accountant', 'Biostatistician III', 'Compensation Analyst',
                   'Associate Professor', 'Social Worker', 'Chemical Engineer', 'Cost Accountant',
                   'Computer Systems Analyst IV', 'Safety Technician I', 'Sales Representative',
                   'Automation Specialist I', 'Help Desk Technician', 'Marketing Manager', 'VP Quality Control',
                   'Developer I', 'Human Resources Assistant I', 'Research Associate', 'Librarian', 'Geologist III',
                   'Speech Pathologist', 'Research Assistant III', 'Physical Therapy Assistant', 'Help Desk Operator',
                   'Account Representative IV', 'Nurse', 'VP Product Management', 'Dental Hygienist', 'Professor',
                   'Chemical Engineer', 'VP Quality Control', 'Product Engineer', 'Research Assistant II',
                   'Clinical Specialist', 'VP Accounting', 'Engineer II', 'Web Developer II', 'Environmental Tech',
                   'Associate Professor', 'Sales Representative', 'Statistician III', 'Assistant Manager',
                   'Budget/Accounting Analyst II', 'Account Executive', 'Senior Cost Accountant', 'Associate Professor',
                   'Systems Administrator III', 'Project Manager', 'VP Sales', 'Administrative Assistant III',
                   'Legal Assistant', 'Internal Auditor', 'Geological Engineer', 'Compensation Analyst',
                   'Automation Specialist IV', 'Senior Financial Analyst', 'Automation Specialist II',
                   'Software Consultant', 'Recruiting Manager', 'Safety Technician IV', 'Help Desk Technician',
                   'Senior Sales Associate', 'Paralegal', 'Environmental Specialist', 'Media Manager IV',
                   'Analog Circuit Design manager', 'Quality Control Specialist', 'Administrative Officer',
                   'Systems Administrator I', 'Assistant Professor', 'Structural Engineer', 'Research Associate',
                   'Civil Engineer', 'Executive Secretary', 'Project Manager', 'Budget/Accounting Analyst III',
                   'Analog Circuit Design manager', 'Mechanical Systems Engineer', 'Associate Professor',
                   'Software Engineer II', 'Marketing Assistant', 'Staff Accountant II', 'GIS Technical Architect',
                   'Financial Advisor', 'Associate Professor', 'Computer Systems Analyst II',
                   'Information Systems Manager', 'Research Nurse', 'Sales Representative',
                   'Database Administrator III', 'Internal Auditor', 'Teacher', 'Computer Systems Analyst I',
                   'Staff Accountant IV', 'Occupational Therapist', 'Assistant Manager', 'Staff Scientist',
                   'Pharmacist', 'Community Outreach Specialist', 'Dental Hygienist', 'Project Manager',
                   'Senior Developer', 'Senior Cost Accountant', 'Account Executive', 'Staff Scientist',
                   'VP Accounting', 'Paralegal', 'Chemical Engineer', 'Environmental Specialist',
                   'Software Test Engineer II', 'Senior Quality Engineer', 'Software Engineer I', 'Actuary',
                   'Dental Hygienist', 'Assistant Manager', 'Automation Specialist II', 'Project Manager',
                   'Marketing Manager', 'Structural Engineer', 'Staff Accountant IV', 'Compensation Analyst',
                   'VP Quality Control', 'Human Resources Assistant II', 'Web Developer IV', 'Media Manager I',
                   'Design Engineer', 'Financial Advisor', 'Pharmacist', 'Assistant Media Planner', 'Legal Assistant',
                   'Programmer Analyst III', 'Office Assistant I', 'Associate Professor', 'Structural Engineer',
                   'Analog Circuit Design manager', 'Marketing Manager', 'Compensation Analyst', 'Chemical Engineer',
                   'Registered Nurse', 'Staff Scientist', 'Help Desk Technician', 'Senior Developer', 'Engineer II',
                   'Account Coordinator', 'Marketing Assistant', 'Paralegal', 'Project Manager', 'Senior Developer',
                   'Research Associate', 'Sales Representative', 'Senior Cost Accountant', 'Senior Cost Accountant',
                   'Senior Cost Accountant', 'Help Desk Operator', 'Paralegal', 'VP Accounting', 'Programmer I',
                   'Media Manager I', 'Human Resources Assistant III', 'Product Engineer', 'Account Coordinator',
                   'Geological Engineer', 'Account Representative I', 'Database Administrator II',
                   'Accounting Assistant I', 'Media Manager IV', 'Database Administrator IV', 'Senior Sales Associate',
                   'General Manager', 'Marketing Manager', 'Research Assistant IV', 'Web Designer I', 'Staff Scientist',
                   'Engineer IV', 'Programmer Analyst II', 'Nuclear Power Engineer', 'Associate Professor',
                   'Sales Associate', 'Executive Secretary', 'Research Assistant II', 'Desktop Support Technician',
                   'Pharmacist', 'Pharmacist', 'Environmental Specialist', 'VP Sales', 'Senior Cost Accountant',
                   'Programmer Analyst I', 'Electrical Engineer', 'Recruiting Manager', 'Senior Cost Accountant',
                   'Environmental Tech', 'Chief Design Engineer', 'Legal Assistant', 'Budget/Accounting Analyst IV',
                   'Recruiter', 'Nurse Practicioner', 'Recruiter', 'Electrical Engineer', 'Environmental Specialist',
                   'Recruiter', 'Mechanical Systems Engineer', 'Research Associate', 'Senior Sales Associate',
                   'Research Associate', 'Help Desk Technician', 'Media Manager IV', 'VP Accounting',
                   'Registered Nurse', 'Safety Technician IV', 'Electrical Engineer', 'Graphic Designer',
                   'Staff Accountant IV', 'Graphic Designer', 'Teacher', 'Recruiter', 'Quality Control Specialist',
                   'Nurse Practicioner', 'Operator', 'Operator', 'Staff Scientist',
                   'Business Systems Development Analyst', 'Pharmacist', 'Assistant Manager', 'Analyst Programmer',
                   'Physical Therapy Assistant', 'Budget/Accounting Analyst I', 'Human Resources Assistant IV',
                   'General Manager', 'Senior Editor', 'Data Coordiator', 'Senior Quality Engineer', 'Programmer II',
                   'Account Coordinator', 'Human Resources Manager', 'Help Desk Technician', 'Recruiter',
                   'Financial Analyst', 'Senior Quality Engineer', 'Research Nurse', 'Recruiter',
                   'Information Systems Manager', 'Web Designer IV', 'Engineer III', 'Human Resources Assistant II',
                   'Librarian', 'Web Developer II', 'Budget/Accounting Analyst IV', 'Account Representative II',
                   'Analog Circuit Design manager', 'Help Desk Technician', 'VP Quality Control', 'Internal Auditor',
                   'GIS Technical Architect', 'Structural Engineer', 'Recruiting Manager', 'Physical Therapy Assistant',
                   'Product Engineer', 'Web Developer IV', 'Computer Systems Analyst II', 'Analyst Programmer',
                   'Accounting Assistant III', 'Office Assistant IV', 'Staff Scientist', 'Senior Quality Engineer',
                   'Assistant Media Planner', 'General Manager', 'Administrative Assistant II', 'Chemical Engineer',
                   'Software Test Engineer III', 'Social Worker', 'Programmer IV', 'Graphic Designer',
                   'Payment Adjustment Coordinator', 'Media Manager IV', 'Environmental Specialist',
                   'Assistant Manager', 'Nurse', 'Teacher', 'Software Engineer III', 'Assistant Media Planner',
                   'Community Outreach Specialist', 'Payment Adjustment Coordinator', 'Community Outreach Specialist',
                   'Quality Engineer', 'Editor', 'Statistician II', 'Senior Quality Engineer', 'Marketing Assistant',
                   'Senior Sales Associate', 'Structural Engineer', 'Nurse', 'Human Resources Manager',
                   'Community Outreach Specialist', 'Help Desk Technician', 'Web Developer II', 'Editor', 'Editor',
                   'Nuclear Power Engineer', 'Teacher', 'Structural Analysis Engineer', 'Food Chemist',
                   'Civil Engineer', 'Computer Systems Analyst IV', 'Quality Engineer', 'Budget/Accounting Analyst III',
                   'Programmer Analyst IV', 'Financial Advisor', 'Office Assistant I', 'Product Engineer',
                   'Data Coordiator', 'Chief Design Engineer', 'Research Associate', 'Web Developer IV',
                   'Quality Engineer', 'Sales Associate', 'Help Desk Operator', 'Engineer I', 'Senior Developer',
                   'Senior Editor', 'Database Administrator III', 'Mechanical Systems Engineer', 'Product Engineer',
                   'Recruiting Manager', 'Web Developer III', 'Computer Systems Analyst III',
                   'Database Administrator III', 'Budget/Accounting Analyst I', 'Data Coordiator',
                   'Software Engineer II', 'Safety Technician III', 'Programmer IV', 'GIS Technical Architect',
                   'Dental Hygienist', 'Social Worker', 'Administrative Officer', 'Legal Assistant',
                   'Marketing Manager', 'Software Engineer II', 'Account Coordinator', 'Senior Editor',
                   'Director of Sales', 'Chemical Engineer', 'VP Accounting', 'Product Engineer', 'Recruiting Manager',
                   'Marketing Manager', 'Junior Executive', 'Nurse', 'Programmer I', 'Mechanical Systems Engineer',
                   'Desktop Support Technician', 'Desktop Support Technician', 'Librarian', 'Dental Hygienist',
                   'Help Desk Technician', 'Teacher', 'Staff Accountant III', 'Financial Analyst', 'Research Nurse',
                   'Professor', 'Recruiter', 'Administrative Officer', 'Business Systems Development Analyst',
                   'Project Manager', 'Staff Scientist', 'Engineer II', 'Software Test Engineer I',
                   'Desktop Support Technician', 'Marketing Assistant', 'Data Coordiator', 'Social Worker',
                   'Sales Associate', 'Human Resources Assistant III', 'Administrative Officer', 'Chemical Engineer',
                   'Financial Analyst', 'Graphic Designer', 'Actuary', 'Data Coordiator', 'Internal Auditor',
                   'Help Desk Operator', 'Financial Advisor', 'Account Executive', 'Information Systems Manager',
                   'Marketing Assistant', 'Executive Secretary', 'General Manager', 'Social Worker', 'Recruiter',
                   'VP Marketing', 'VP Marketing', 'Safety Technician IV', 'Nurse', 'Accounting Assistant II',
                   'Chemical Engineer', 'Senior Cost Accountant', 'Account Executive', 'Occupational Therapist',
                   'Database Administrator IV', 'Software Test Engineer III', 'Account Coordinator',
                   'Executive Secretary', 'Information Systems Manager', 'Senior Financial Analyst', 'Engineer I',
                   'Speech Pathologist', 'Tax Accountant', 'Accounting Assistant II', 'Quality Control Specialist',
                   'Web Designer III', 'Nuclear Power Engineer', 'Account Executive', 'Electrical Engineer',
                   'Product Engineer', 'Chemical Engineer', 'Information Systems Manager', 'Graphic Designer',
                   'Developer IV', 'Senior Developer', 'Actuary', 'Human Resources Manager',
                   'Analog Circuit Design manager', 'Computer Systems Analyst IV', 'Community Outreach Specialist',
                   'VP Sales', 'Product Engineer', 'Environmental Tech', 'Recruiter', 'VP Quality Control',
                   'GIS Technical Architect', 'Biostatistician II', 'Senior Cost Accountant',
                   'Computer Systems Analyst II', 'Operator', 'Software Consultant', 'Administrative Assistant II',
                   'Computer Systems Analyst II', 'Engineer II', 'Marketing Assistant', 'Software Engineer III',
                   'Occupational Therapist', 'Editor', 'Director of Sales', 'Recruiter', 'Marketing Assistant',
                   'Biostatistician IV', 'Electrical Engineer', 'Biostatistician IV', 'Senior Quality Engineer',
                   'Staff Scientist', 'Computer Systems Analyst I', 'Legal Assistant', 'Professor',
                   'Administrative Officer', 'Financial Advisor', 'Food Chemist', 'Civil Engineer', 'Food Chemist',
                   'Systems Administrator II', 'Nuclear Power Engineer', 'Internal Auditor', 'Assistant Media Planner',
                   'Administrative Assistant II', 'Clinical Specialist', 'Recruiting Manager', 'Assistant Professor',
                   'Professor', 'Director of Sales', 'Human Resources Manager', 'Geologist I', 'Tax Accountant',
                   'Geologist III', 'Systems Administrator III', 'Software Consultant', 'Developer IV',
                   'General Manager', 'Programmer IV', 'Social Worker', 'GIS Technical Architect',
                   'Payment Adjustment Coordinator', 'Software Engineer III', 'Media Manager IV', 'Web Designer II',
                   'Chief Design Engineer', 'Business Systems Development Analyst', 'Desktop Support Technician',
                   'Staff Accountant I', 'Actuary', 'Editor', 'Junior Executive', 'Chief Design Engineer',
                   'Chief Design Engineer', 'Tax Accountant', 'Senior Quality Engineer', 'Operator', 'Project Manager',
                   'Professor', 'VP Accounting', 'Project Manager', 'Nurse Practicioner', 'Nurse Practicioner',
                   'Account Executive', 'Legal Assistant', 'Actuary', 'Marketing Assistant', 'Chief Design Engineer',
                   'Chemical Engineer', 'Help Desk Operator', 'Nuclear Power Engineer', 'Administrative Assistant II',
                   'Senior Developer', 'Staff Accountant II', 'Software Engineer II', 'Social Worker',
                   'Automation Specialist III', 'Software Engineer I', 'Environmental Specialist', 'Account Executive',
                   'Chief Design Engineer', 'Actuary', 'Structural Engineer', 'Financial Advisor', 'Speech Pathologist',
                   'Administrative Officer', 'Graphic Designer', 'Cost Accountant', 'Community Outreach Specialist',
                   'Business Systems Development Analyst', 'Statistician III', 'Account Representative III',
                   'Compensation Analyst', 'Geologist II', 'Database Administrator II', 'Media Manager I',
                   'Sales Associate', 'Analyst Programmer', 'Quality Control Specialist', 'Professor',
                   'Compensation Analyst', 'Technical Writer', 'Administrative Officer', 'Occupational Therapist',
                   'Budget/Accounting Analyst II', 'Automation Specialist IV', 'Desktop Support Technician',
                   'Technical Writer', 'VP Product Management', 'Information Systems Manager', 'Engineer IV', 'Editor',
                   'Paralegal', 'Nurse Practicioner', 'VP Accounting', 'Administrative Officer', 'Sales Associate',
                   'Analyst Programmer', 'Operator', 'Marketing Assistant', 'Business Systems Development Analyst',
                   'Desktop Support Technician', 'Payment Adjustment Coordinator', 'Assistant Manager',
                   'Senior Sales Associate', 'Account Representative I', 'Web Designer IV', 'Social Worker',
                   'Human Resources Manager', 'Budget/Accounting Analyst I', 'Information Systems Manager',
                   'Research Assistant I', 'Human Resources Manager', 'Social Worker', 'Chemical Engineer',
                   'Research Assistant III', 'Quality Control Specialist', 'Financial Advisor', 'Actuary',
                   'Analyst Programmer', 'Financial Analyst', 'Editor', 'Mechanical Systems Engineer',
                   'Payment Adjustment Coordinator', 'Systems Administrator II', 'Research Nurse',
                   'Software Engineer IV', 'Statistician I', 'Associate Professor', 'Assistant Manager',
                   'Electrical Engineer', 'Librarian', 'Automation Specialist I', 'VP Quality Control',
                   'Research Assistant II', 'Social Worker', 'Budget/Accounting Analyst I', 'Assistant Manager',
                   'VP Quality Control', 'Geologist IV', 'Budget/Accounting Analyst IV', 'Financial Analyst',
                   'Civil Engineer', 'Administrative Officer', 'Data Coordiator', 'Operator', 'Technical Writer',
                   'Recruiting Manager', 'Data Coordiator', 'Senior Financial Analyst', 'Analog Circuit Design manager',
                   'Human Resources Assistant I', 'Senior Sales Associate', 'Executive Secretary', 'Food Chemist',
                   'Community Outreach Specialist', 'Geologist III', 'Editor', 'Assistant Professor',
                   'Automation Specialist IV', 'Research Associate', 'Research Assistant II', 'Tax Accountant',
                   'Marketing Assistant', 'Occupational Therapist', 'Financial Analyst', 'Legal Assistant',
                   'Registered Nurse', 'Automation Specialist III', 'Teacher', 'Desktop Support Technician',
                   'Librarian', 'Speech Pathologist', 'Engineer III', 'Assistant Media Planner', 'Director of Sales',
                   'Teacher', 'Social Worker', 'Safety Technician II', 'Recruiting Manager', 'Office Assistant I',
                   'Senior Quality Engineer', 'Recruiting Manager', 'Computer Systems Analyst III', 'Assistant Manager',
                   'Sales Representative', 'Environmental Tech', 'Analyst Programmer', 'Financial Analyst',
                   'Business Systems Development Analyst', 'Professor', 'Technical Writer', 'Senior Editor',
                   'General Manager', 'Software Test Engineer I', 'Staff Accountant II', 'Media Manager I',
                   'Web Developer IV', 'Human Resources Manager', 'Physical Therapy Assistant', 'Analyst Programmer',
                   'Account Coordinator', 'Civil Engineer', 'Chemical Engineer', 'Senior Editor', 'Cost Accountant',
                   'Graphic Designer', 'Marketing Assistant', 'Assistant Manager', 'Quality Engineer',
                   'Structural Engineer', 'Executive Secretary', 'Structural Analysis Engineer', 'Registered Nurse',
                   'Administrative Assistant III', 'Information Systems Manager', 'Account Representative II',
                   'Nuclear Power Engineer', 'Administrative Officer', 'Payment Adjustment Coordinator',
                   'Web Developer III']

        p_nouns = ["These dudes", "Both of my moms", "All the kings of the world", "Some guys",
                   "All of a cattery's cats",
                   "The multitude of sloths living under your bed", "Your homies",
                   "Like, these, like, all these people",
                   "Supermen", 'Human Resources Managers', 'Accountant IVs', 'Desktop Support Technicians',
                   'General Managers', 'Actuarys', 'Biostatistician IIIs', 'Financial Analysts',
                   'Senior Cost Accountants', 'Civil Engineers', 'Marketing Assistants', 'Professors',
                   'GIS Technical Architects', 'Office Assistant Is', 'Director of Saless', 'Operators',
                   'Associate Professors', 'Senior Editors', 'Tax Accountants', 'Help Desk Operators',
                   'Nuclear Power Engineers', 'Sales Associates', 'Actuarys', 'Office Assistant Is',
                   'Research Associates', 'Senior Sales Associates', 'Account Executives', 'Account Executives',
                   'VP Marketings', 'VP Saless', 'Human Resources Managers', 'Actuarys', 'Administrative Assistant IVs',
                   'Actuarys', 'Social Workers', 'Chief Design Engineers', 'Graphic Designers', 'VP Marketings',
                   'Assistant Managers', 'Senior Cost Accountants', 'Administrative Assistant IIIs',
                   'Software Test Engineer IIs', 'Human Resources Assistant IVs', 'Dental Hygienists',
                   'Project Managers', 'Administrative Officers', 'Environmental Techs', 'Account Representative IIs',
                   'Associate Professors', 'Programmer Analyst IIIs', 'Health Coach Is', 'Research Associates',
                   'Administrative Assistant IVs', 'Junior Executives', 'Registered Nurses', 'Office Assistant IVs',
                   'Librarians', 'Librarians', 'Occupational Therapists', 'Financial Advisors', 'Senior Developers',
                   'Staff Accountant IIs', 'Speech Pathologists', 'Research Assistant IVs', 'Accountant IVs',
                   'VP Quality Controls', 'Executive Secretarys', 'Accounting Assistant IIIs', 'Director of Saless',
                   'Research Assistant Is', 'Human Resources Assistant IIIs', 'Accountant IIs', 'Safety Technician Is',
                   'Technical Writers', 'VP Marketings', 'Help Desk Operators', 'Senior Quality Engineers',
                   'Financial Analysts', 'Office Assistant IVs', 'Programmer IIIs', 'Help Desk Technicians',
                   'Recruiting Managers', 'Human Resources Assistant Is', 'Librarians', 'Dental Hygienists',
                   'General Managers', 'Staff Accountant Is', 'Research Assistant IIIs', 'Research Nurses',
                   'Paralegals', 'VP Marketings', 'Budget/Accounting Analyst IVs', 'Help Desk Operators',
                   'Nurse Practicioners', 'Quality Control Specialists', 'VP Marketings', 'Programmer IVs',
                   'Web Designer IIs', 'Human Resources Managers', 'Junior Executives', 'Tax Accountants', 'Editors',
                   'Biostatistician Is', 'Structural Engineers', 'Statistician Is', 'Software Test Engineer IIIs',
                   'Research Associates', 'Editors', 'Software Consultants', 'Accountant IIIs',
                   'Occupational Therapists', 'VP Saless', 'Desktop Support Technicians', 'Senior Sales Associates',
                   'Clinical Specialists', 'Analyst Programmers', 'Geologist Is', 'Graphic Designers',
                   'Research Associates', 'Structural Analysis Engineers', 'Biostatistician Is', 'Registered Nurses',
                   'VP Marketings', 'Database Administrator IIIs', 'Geological Engineers', 'Office Assistant IVs',
                   'Marketing Managers', 'Staff Accountant IIs', 'Occupational Therapists', 'VP Quality Controls',
                   'Paralegals', 'Research Associates', 'Physical Therapy Assistants', 'Pharmacists', 'Pharmacists',
                   'Account Executives', 'Media Manager IVs', 'GIS Technical Architects',
                   'Budget/Accounting Analyst Is', 'Senior Developers', 'Structural Engineers', 'Assistant Managers',
                   'Database Administrator IIIs', 'VP Marketings', 'Office Assistant IIIs', 'Tax Accountants',
                   'Software Consultants', 'Biostatistician IVs', 'Senior Cost Accountants', 'VP Marketings',
                   'Executive Secretarys', 'Pharmacists', 'Programmer Analyst IVs', 'Programmer Is',
                   'Assistant Professors', 'Civil Engineers', 'Registered Nurses', 'Statistician Is',
                   'Staff Accountant IVs', 'Mechanical Systems Engineers', 'Design Engineers', 'Financial Advisors',
                   'VP Accountings', 'Nurse Practicioners', 'General Managers', 'Software Engineer Is',
                   'Safety Technician IVs', 'Accounting Assistant IIs', 'Registered Nurses', 'Chemical Engineers',
                   'Marketing Managers', 'Nuclear Power Engineers', 'Quality Control Specialists',
                   'Automation Specialist IIs', 'VP Product Managements', 'Statistician IVs',
                   'Payment Adjustment Coordinators', 'VP Product Managements', 'Engineer IIIs', 'Legal Assistants',
                   'Recruiting Managers', 'Biostatistician IIIs', 'Legal Assistants', 'Executive Secretarys',
                   'Database Administrator IIs', 'Financial Analysts', 'Statistician IVs', 'Nuclear Power Engineers',
                   'Cost Accountants', 'Geological Engineers', 'Teachers', 'General Managers', 'Design Engineers',
                   'Speech Pathologists', 'Assistant Professors', 'Mechanical Systems Engineers', 'Health Coach IIIs',
                   'Analog Circuit Design managers', 'Assistant Media Planners', 'Human Resources Assistant IIs',
                   'Operators', 'Cost Accountants', 'Tax Accountants', 'Biostatistician IIIs',
                   'Account Representative IIIs', 'Developer IIIs', 'Automation Specialist IVs', 'Operators',
                   'Geological Engineers', 'Dental Hygienists', 'Help Desk Operators', 'Legal Assistants',
                   'VP Marketings', 'Human Resources Assistant IIs', 'Civil Engineers', 'Programmer Analyst IIs',
                   'Professors', 'Automation Specialist IIs', 'Electrical Engineers', 'Nurses', 'Web Designer Is',
                   'Automation Specialist IVs', 'Pharmacists', 'Actuarys', 'General Managers', 'Help Desk Operators',
                   'Geological Engineers', 'Design Engineers', 'VP Marketings', 'Accounting Assistant IIIs',
                   'Occupational Therapists', 'Compensation Analysts', 'Junior Executives', 'Administrative Officers',
                   'Programmer Analyst IVs', 'Account Executives', 'Senior Cost Accountants',
                   'Senior Quality Engineers', 'Civil Engineers', 'VP Accountings', 'Assistant Media Planners',
                   'Accountant Is', 'Nuclear Power Engineers', 'Professors', 'Technical Writers', 'Recruiters',
                   'Staff Accountant IIs', 'Occupational Therapists', 'Staff Accountant IIs', 'Sales Associates',
                   'Director of Saless', 'Environmental Techs', 'Research Assistant IIs', 'Tax Accountants',
                   'Senior Developers', 'Data Coordiators', 'Junior Executives', 'Office Assistant IIs',
                   'Recruiting Managers', 'Programmer Analyst IVs', 'Teachers', 'Research Nurses',
                   'Assistant Media Planners', 'VP Quality Controls', 'Payment Adjustment Coordinators',
                   'VP Accountings', 'Environmental Specialists', 'Internal Auditors', 'Statistician IVs', 'Professors',
                   'Civil Engineers', 'Design Engineers', 'Senior Editors', 'Junior Executives', 'Cost Accountants',
                   'Pharmacists', 'Analog Circuit Design managers', 'Environmental Specialists',
                   'Physical Therapy Assistants', 'Senior Financial Analysts', 'Geologist IIs', 'Electrical Engineers',
                   'Analog Circuit Design managers', 'Design Engineers', 'Human Resources Assistant IVs',
                   'Graphic Designers', 'Senior Editors', 'Business Systems Development Analysts',
                   'Geological Engineers', 'Operators', 'Staff Accountant Is', 'Help Desk Operators',
                   'Systems Administrator Is', 'Environmental Specialists', 'VP Saless', 'GIS Technical Architects',
                   'Environmental Techs', 'Programmer Analyst IIs', 'Help Desk Technicians', 'Web Designer IVs',
                   'Design Engineers', 'Mechanical Systems Engineers', 'Geologist IVs', 'Engineer IIIs',
                   'Clinical Specialists', 'Account Coordinators', 'Account Executives', 'Software Test Engineer IIIs',
                   'Executive Secretarys', 'Research Assistant IIs', 'Software Test Engineer Is', 'Nurses',
                   'Technical Writers', 'Data Coordiators', 'Programmer IIs', 'Food Chemists',
                   'Software Test Engineer Is', 'Senior Developers', 'Sales Representatives', 'Librarians',
                   'Project Managers', 'VP Marketings', 'Occupational Therapists', 'Senior Cost Accountants',
                   'Biostatistician IIIs', 'Compensation Analysts', 'Associate Professors', 'Social Workers',
                   'Chemical Engineers', 'Cost Accountants', 'Computer Systems Analyst IVs', 'Safety Technician Is',
                   'Sales Representatives', 'Automation Specialist Is', 'Help Desk Technicians', 'Marketing Managers',
                   'VP Quality Controls', 'Developer Is', 'Human Resources Assistant Is', 'Research Associates',
                   'Librarians', 'Geologist IIIs', 'Speech Pathologists', 'Research Assistant IIIs',
                   'Physical Therapy Assistants', 'Help Desk Operators', 'Account Representative IVs', 'Nurses',
                   'VP Product Managements', 'Dental Hygienists', 'Professors', 'Chemical Engineers',
                   'VP Quality Controls', 'Product Engineers', 'Research Assistant IIs', 'Clinical Specialists',
                   'VP Accountings', 'Engineer IIs', 'Web Developer IIs', 'Environmental Techs', 'Associate Professors',
                   'Sales Representatives', 'Statistician IIIs', 'Assistant Managers', 'Budget/Accounting Analyst IIs',
                   'Account Executives', 'Senior Cost Accountants', 'Associate Professors',
                   'Systems Administrator IIIs', 'Project Managers', 'VP Saless', 'Administrative Assistant IIIs',
                   'Legal Assistants', 'Internal Auditors', 'Geological Engineers', 'Compensation Analysts',
                   'Automation Specialist IVs', 'Senior Financial Analysts', 'Automation Specialist IIs',
                   'Software Consultants', 'Recruiting Managers', 'Safety Technician IVs', 'Help Desk Technicians',
                   'Senior Sales Associates', 'Paralegals', 'Environmental Specialists', 'Media Manager IVs',
                   'Analog Circuit Design managers', 'Quality Control Specialists', 'Administrative Officers',
                   'Systems Administrator Is', 'Assistant Professors', 'Structural Engineers', 'Research Associates',
                   'Civil Engineers', 'Executive Secretarys', 'Project Managers', 'Budget/Accounting Analyst IIIs',
                   'Analog Circuit Design managers', 'Mechanical Systems Engineers', 'Associate Professors',
                   'Software Engineer IIs', 'Marketing Assistants', 'Staff Accountant IIs', 'GIS Technical Architects',
                   'Financial Advisors', 'Associate Professors', 'Computer Systems Analyst IIs',
                   'Information Systems Managers', 'Research Nurses', 'Sales Representatives',
                   'Database Administrator IIIs', 'Internal Auditors', 'Teachers', 'Computer Systems Analyst Is',
                   'Staff Accountant IVs', 'Occupational Therapists', 'Assistant Managers', 'Staff Scientists',
                   'Pharmacists', 'Community Outreach Specialists', 'Dental Hygienists', 'Project Managers',
                   'Senior Developers', 'Senior Cost Accountants', 'Account Executives', 'Staff Scientists',
                   'VP Accountings', 'Paralegals', 'Chemical Engineers', 'Environmental Specialists',
                   'Software Test Engineer IIs', 'Senior Quality Engineers', 'Software Engineer Is', 'Actuarys',
                   'Dental Hygienists', 'Assistant Managers', 'Automation Specialist IIs', 'Project Managers',
                   'Marketing Managers', 'Structural Engineers', 'Staff Accountant IVs', 'Compensation Analysts',
                   'VP Quality Controls', 'Human Resources Assistant IIs', 'Web Developer IVs', 'Media Manager Is',
                   'Design Engineers', 'Financial Advisors', 'Pharmacists', 'Assistant Media Planners',
                   'Legal Assistants', 'Programmer Analyst IIIs', 'Office Assistant Is', 'Associate Professors',
                   'Structural Engineers', 'Analog Circuit Design managers', 'Marketing Managers',
                   'Compensation Analysts', 'Chemical Engineers', 'Registered Nurses', 'Staff Scientists',
                   'Help Desk Technicians', 'Senior Developers', 'Engineer IIs', 'Account Coordinators',
                   'Marketing Assistants', 'Paralegals', 'Project Managers', 'Senior Developers', 'Research Associates',
                   'Sales Representatives', 'Senior Cost Accountants', 'Senior Cost Accountants',
                   'Senior Cost Accountants', 'Help Desk Operators', 'Paralegals', 'VP Accountings', 'Programmer Is',
                   'Media Manager Is', 'Human Resources Assistant IIIs', 'Product Engineers', 'Account Coordinators',
                   'Geological Engineers', 'Account Representative Is', 'Database Administrator IIs',
                   'Accounting Assistant Is', 'Media Manager IVs', 'Database Administrator IVs',
                   'Senior Sales Associates', 'General Managers', 'Marketing Managers', 'Research Assistant IVs',
                   'Web Designer Is', 'Staff Scientists', 'Engineer IVs', 'Programmer Analyst IIs',
                   'Nuclear Power Engineers', 'Associate Professors', 'Sales Associates', 'Executive Secretarys',
                   'Research Assistant IIs', 'Desktop Support Technicians', 'Pharmacists', 'Pharmacists',
                   'Environmental Specialists', 'VP Saless', 'Senior Cost Accountants', 'Programmer Analyst Is',
                   'Electrical Engineers', 'Recruiting Managers', 'Senior Cost Accountants', 'Environmental Techs',
                   'Chief Design Engineers', 'Legal Assistants', 'Budget/Accounting Analyst IVs', 'Recruiters',
                   'Nurse Practicioners', 'Recruiters', 'Electrical Engineers', 'Environmental Specialists',
                   'Recruiters', 'Mechanical Systems Engineers', 'Research Associates', 'Senior Sales Associates',
                   'Research Associates', 'Help Desk Technicians', 'Media Manager IVs', 'VP Accountings',
                   'Registered Nurses', 'Safety Technician IVs', 'Electrical Engineers', 'Graphic Designers',
                   'Staff Accountant IVs', 'Graphic Designers', 'Teachers', 'Recruiters', 'Quality Control Specialists',
                   'Nurse Practicioners', 'Operators', 'Operators', 'Staff Scientists',
                   'Business Systems Development Analysts', 'Pharmacists', 'Assistant Managers', 'Analyst Programmers',
                   'Physical Therapy Assistants', 'Budget/Accounting Analyst Is', 'Human Resources Assistant IVs',
                   'General Managers', 'Senior Editors', 'Data Coordiators', 'Senior Quality Engineers',
                   'Programmer IIs', 'Account Coordinators', 'Human Resources Managers', 'Help Desk Technicians',
                   'Recruiters', 'Financial Analysts', 'Senior Quality Engineers', 'Research Nurses', 'Recruiters',
                   'Information Systems Managers', 'Web Designer IVs', 'Engineer IIIs', 'Human Resources Assistant IIs',
                   'Librarians', 'Web Developer IIs', 'Budget/Accounting Analyst IVs', 'Account Representative IIs',
                   'Analog Circuit Design managers', 'Help Desk Technicians', 'VP Quality Controls',
                   'Internal Auditors', 'GIS Technical Architects', 'Structural Engineers', 'Recruiting Managers',
                   'Physical Therapy Assistants', 'Product Engineers', 'Web Developer IVs',
                   'Computer Systems Analyst IIs', 'Analyst Programmers', 'Accounting Assistant IIIs',
                   'Office Assistant IVs', 'Staff Scientists', 'Senior Quality Engineers', 'Assistant Media Planners',
                   'General Managers', 'Administrative Assistant IIs', 'Chemical Engineers',
                   'Software Test Engineer IIIs', 'Social Workers', 'Programmer IVs', 'Graphic Designers',
                   'Payment Adjustment Coordinators', 'Media Manager IVs', 'Environmental Specialists',
                   'Assistant Managers', 'Nurses', 'Teachers', 'Software Engineer IIIs', 'Assistant Media Planners',
                   'Community Outreach Specialists', 'Payment Adjustment Coordinators',
                   'Community Outreach Specialists', 'Quality Engineers', 'Editors', 'Statistician IIs',
                   'Senior Quality Engineers', 'Marketing Assistants', 'Senior Sales Associates',
                   'Structural Engineers', 'Nurses', 'Human Resources Managers', 'Community Outreach Specialists',
                   'Help Desk Technicians', 'Web Developer IIs', 'Editors', 'Editors', 'Nuclear Power Engineers',
                   'Teachers', 'Structural Analysis Engineers', 'Food Chemists', 'Civil Engineers',
                   'Computer Systems Analyst IVs', 'Quality Engineers', 'Budget/Accounting Analyst IIIs',
                   'Programmer Analyst IVs', 'Financial Advisors', 'Office Assistant Is', 'Product Engineers',
                   'Data Coordiators', 'Chief Design Engineers', 'Research Associates', 'Web Developer IVs',
                   'Quality Engineers', 'Sales Associates', 'Help Desk Operators', 'Engineer Is', 'Senior Developers',
                   'Senior Editors', 'Database Administrator IIIs', 'Mechanical Systems Engineers', 'Product Engineers',
                   'Recruiting Managers', 'Web Developer IIIs', 'Computer Systems Analyst IIIs',
                   'Database Administrator IIIs', 'Budget/Accounting Analyst Is', 'Data Coordiators',
                   'Software Engineer IIs', 'Safety Technician IIIs', 'Programmer IVs', 'GIS Technical Architects',
                   'Dental Hygienists', 'Social Workers', 'Administrative Officers', 'Legal Assistants',
                   'Marketing Managers', 'Software Engineer IIs', 'Account Coordinators', 'Senior Editors',
                   'Director of Saless', 'Chemical Engineers', 'VP Accountings', 'Product Engineers',
                   'Recruiting Managers', 'Marketing Managers', 'Junior Executives', 'Nurses', 'Programmer Is',
                   'Mechanical Systems Engineers', 'Desktop Support Technicians', 'Desktop Support Technicians',
                   'Librarians', 'Dental Hygienists', 'Help Desk Technicians', 'Teachers', 'Staff Accountant IIIs',
                   'Financial Analysts', 'Research Nurses', 'Professors', 'Recruiters', 'Administrative Officers',
                   'Business Systems Development Analysts', 'Project Managers', 'Staff Scientists', 'Engineer IIs',
                   'Software Test Engineer Is', 'Desktop Support Technicians', 'Marketing Assistants',
                   'Data Coordiators', 'Social Workers', 'Sales Associates', 'Human Resources Assistant IIIs',
                   'Administrative Officers', 'Chemical Engineers', 'Financial Analysts', 'Graphic Designers',
                   'Actuarys', 'Data Coordiators', 'Internal Auditors', 'Help Desk Operators', 'Financial Advisors',
                   'Account Executives', 'Information Systems Managers', 'Marketing Assistants', 'Executive Secretarys',
                   'General Managers', 'Social Workers', 'Recruiters', 'VP Marketings', 'VP Marketings',
                   'Safety Technician IVs', 'Nurses', 'Accounting Assistant IIs', 'Chemical Engineers',
                   'Senior Cost Accountants', 'Account Executives', 'Occupational Therapists',
                   'Database Administrator IVs', 'Software Test Engineer IIIs', 'Account Coordinators',
                   'Executive Secretarys', 'Information Systems Managers', 'Senior Financial Analysts', 'Engineer Is',
                   'Speech Pathologists', 'Tax Accountants', 'Accounting Assistant IIs', 'Quality Control Specialists',
                   'Web Designer IIIs', 'Nuclear Power Engineers', 'Account Executives', 'Electrical Engineers',
                   'Product Engineers', 'Chemical Engineers', 'Information Systems Managers', 'Graphic Designers',
                   'Developer IVs', 'Senior Developers', 'Actuarys', 'Human Resources Managers',
                   'Analog Circuit Design managers', 'Computer Systems Analyst IVs', 'Community Outreach Specialists',
                   'VP Saless', 'Product Engineers', 'Environmental Techs', 'Recruiters', 'VP Quality Controls',
                   'GIS Technical Architects', 'Biostatistician IIs', 'Senior Cost Accountants',
                   'Computer Systems Analyst IIs', 'Operators', 'Software Consultants', 'Administrative Assistant IIs',
                   'Computer Systems Analyst IIs', 'Engineer IIs', 'Marketing Assistants', 'Software Engineer IIIs',
                   'Occupational Therapists', 'Editors', 'Director of Saless', 'Recruiters', 'Marketing Assistants',
                   'Biostatistician IVs', 'Electrical Engineers', 'Biostatistician IVs', 'Senior Quality Engineers',
                   'Staff Scientists', 'Computer Systems Analyst Is', 'Legal Assistants', 'Professors',
                   'Administrative Officers', 'Financial Advisors', 'Food Chemists', 'Civil Engineers', 'Food Chemists',
                   'Systems Administrator IIs', 'Nuclear Power Engineers', 'Internal Auditors',
                   'Assistant Media Planners', 'Administrative Assistant IIs', 'Clinical Specialists',
                   'Recruiting Managers', 'Assistant Professors', 'Professors', 'Director of Saless',
                   'Human Resources Managers', 'Geologist Is', 'Tax Accountants', 'Geologist IIIs',
                   'Systems Administrator IIIs', 'Software Consultants', 'Developer IVs', 'General Managers',
                   'Programmer IVs', 'Social Workers', 'GIS Technical Architects', 'Payment Adjustment Coordinators',
                   'Software Engineer IIIs', 'Media Manager IVs', 'Web Designer IIs', 'Chief Design Engineers',
                   'Business Systems Development Analysts', 'Desktop Support Technicians', 'Staff Accountant Is',
                   'Actuarys', 'Editors', 'Junior Executives', 'Chief Design Engineers', 'Chief Design Engineers',
                   'Tax Accountants', 'Senior Quality Engineers', 'Operators', 'Project Managers', 'Professors',
                   'VP Accountings', 'Project Managers', 'Nurse Practicioners', 'Nurse Practicioners',
                   'Account Executives', 'Legal Assistants', 'Actuarys', 'Marketing Assistants',
                   'Chief Design Engineers', 'Chemical Engineers', 'Help Desk Operators', 'Nuclear Power Engineers',
                   'Administrative Assistant IIs', 'Senior Developers', 'Staff Accountant IIs', 'Software Engineer IIs',
                   'Social Workers', 'Automation Specialist IIIs', 'Software Engineer Is', 'Environmental Specialists',
                   'Account Executives', 'Chief Design Engineers', 'Actuarys', 'Structural Engineers',
                   'Financial Advisors', 'Speech Pathologists', 'Administrative Officers', 'Graphic Designers',
                   'Cost Accountants', 'Community Outreach Specialists', 'Business Systems Development Analysts',
                   'Statistician IIIs', 'Account Representative IIIs', 'Compensation Analysts', 'Geologist IIs',
                   'Database Administrator IIs', 'Media Manager Is', 'Sales Associates', 'Analyst Programmers',
                   'Quality Control Specialists', 'Professors', 'Compensation Analysts', 'Technical Writers',
                   'Administrative Officers', 'Occupational Therapists', 'Budget/Accounting Analyst IIs',
                   'Automation Specialist IVs', 'Desktop Support Technicians', 'Technical Writers',
                   'VP Product Managements', 'Information Systems Managers', 'Engineer IVs', 'Editors', 'Paralegals',
                   'Nurse Practicioners', 'VP Accountings', 'Administrative Officers', 'Sales Associates',
                   'Analyst Programmers', 'Operators', 'Marketing Assistants', 'Business Systems Development Analysts',
                   'Desktop Support Technicians', 'Payment Adjustment Coordinators', 'Assistant Managers',
                   'Senior Sales Associates', 'Account Representative Is', 'Web Designer IVs', 'Social Workers',
                   'Human Resources Managers', 'Budget/Accounting Analyst Is', 'Information Systems Managers',
                   'Research Assistant Is', 'Human Resources Managers', 'Social Workers', 'Chemical Engineers',
                   'Research Assistant IIIs', 'Quality Control Specialists', 'Financial Advisors', 'Actuarys',
                   'Analyst Programmers', 'Financial Analysts', 'Editors', 'Mechanical Systems Engineers',
                   'Payment Adjustment Coordinators', 'Systems Administrator IIs', 'Research Nurses',
                   'Software Engineer IVs', 'Statistician Is', 'Associate Professors', 'Assistant Managers',
                   'Electrical Engineers', 'Librarians', 'Automation Specialist Is', 'VP Quality Controls',
                   'Research Assistant IIs', 'Social Workers', 'Budget/Accounting Analyst Is', 'Assistant Managers',
                   'VP Quality Controls', 'Geologist IVs', 'Budget/Accounting Analyst IVs', 'Financial Analysts',
                   'Civil Engineers', 'Administrative Officers', 'Data Coordiators', 'Operators', 'Technical Writers',
                   'Recruiting Managers', 'Data Coordiators', 'Senior Financial Analysts',
                   'Analog Circuit Design managers', 'Human Resources Assistant Is', 'Senior Sales Associates',
                   'Executive Secretarys', 'Food Chemists', 'Community Outreach Specialists', 'Geologist IIIs',
                   'Editors', 'Assistant Professors', 'Automation Specialist IVs', 'Research Associates',
                   'Research Assistant IIs', 'Tax Accountants', 'Marketing Assistants', 'Occupational Therapists',
                   'Financial Analysts', 'Legal Assistants', 'Registered Nurses', 'Automation Specialist IIIs',
                   'Teachers', 'Desktop Support Technicians', 'Librarians', 'Speech Pathologists', 'Engineer IIIs',
                   'Assistant Media Planners', 'Director of Saless', 'Teachers', 'Social Workers',
                   'Safety Technician IIs', 'Recruiting Managers', 'Office Assistant Is', 'Senior Quality Engineers',
                   'Recruiting Managers', 'Computer Systems Analyst IIIs', 'Assistant Managers',
                   'Sales Representatives', 'Environmental Techs', 'Analyst Programmers', 'Financial Analysts',
                   'Business Systems Development Analysts', 'Professors', 'Technical Writers', 'Senior Editors',
                   'General Managers', 'Software Test Engineer Is', 'Staff Accountant IIs', 'Media Manager Is',
                   'Web Developer IVs', 'Human Resources Managers', 'Physical Therapy Assistants',
                   'Analyst Programmers', 'Account Coordinators', 'Civil Engineers', 'Chemical Engineers',
                   'Senior Editors', 'Cost Accountants', 'Graphic Designers', 'Marketing Assistants',
                   'Assistant Managers', 'Quality Engineers', 'Structural Engineers', 'Executive Secretarys',
                   'Structural Analysis Engineers', 'Registered Nurses', 'Administrative Assistant IIIs',
                   'Information Systems Managers', 'Account Representative IIs', 'Nuclear Power Engineers',
                   'Administrative Officers', 'Payment Adjustment Coordinators', 'Web Developer IIIs']

        s_verbs = ["eats", "kicks", "gives", "treats", "meets with", "creates", "hacks", "configures", "spies on",
                   "retards", "meows on", "flees from", "tries to automate", "explodes"]
        p_verbs = ["eat", "kick", "give", "treat", "meet with", "create", "hack", "configure", "spy on", "retard",
                   "meow on", "flee from", "try to automate", "explode"]
        infinitives = ["to make a pie.", "for no apparent reason.", "because the sky is green.", "for a disease.",
                       "to be able to make toast explode.", "to know more about archeology."]

        import random

        return (random.choice(s_nouns) + " " + random.choice(s_verbs) + " " + random.choice(
            s_nouns).lower() or random.choice(
            p_nouns).lower() + " " + random.choice(p_verbs) + " " + random.choice(infinitives))
