# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:

      - image: circleci/python:3.7.3-stretch-node-browsers

    working_directory: ~/automation-python

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev

      - save_cache:
          paths:
            - ./venv
            - /usr/local/bin
            - /usr/local/lib/python3.7/site-packages
          key: v1-dependencies-{{ checksum "requirements.txt" }}


      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --alluredir=./jira/tests-reports ./jira/tests
      - run:
          name: Reporting
          command:  |
            allure generate -c ./jira/tests-reports
          when: always

      - store_artifacts:
          path: allure-report
          destination: allure-report
          when: always